apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nebulaos-core
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jacksonwendel/nebulaos.git
    targetRevision: HEAD
    path: deploy/local
  destination:
    server: https://kubernetes.default.svc
    namespace: nebulaos
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
